# Generated by Django 2.2.28 on 2023-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poudlard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
