# Generated by Django 2.2.28 on 2023-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poudlard', '0003_auto_20231115_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='famille',
            field=models.CharField(default='Griffondor', max_length=50),
            preserve_default=False,
        ),
    ]
