# Generated by Django 2.2.28 on 2023-11-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poudlard', '0004_character_famille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='famille',
            new_name='maison',
        ),
    ]
